### ISSUE TITLE
Zap DE for lower TH/spell factories

### ISSUE THREAD

**Issue by Stormtrail** [CodeSlinger69/ClAsHbOt#13]
Code,

Was trying to get the Zap DE functionality for my TH7 alternate account, I thought it would be a simple matter of editing the spell count and the for loop but I'm clearly misunderstanding how it works. It seems to recognize even unedited that I have 3/3 lightnings queued and/or ready, but then its not finding acceptable targets.

Just for my own curiosity, since it already seems to grab the correct quantity of spells (from the spell factory?), is there a way to edit those lines such that it will work regardless of TH level?

**Comment by CodeSlinger69** [comment]
Wiki: https://github.com/CodeSlinger69/ClAsHbOt/wiki/History, specifically:

> Does is work at TH7 or lower? I don't know, and I don't care. In my opinion, until TH8, the grind is not a big factor anyway, so why bother with a farm bot before then?

What this means, in a less harsh manner, is that I did not capture images for all the different levels of buildings.  Specifically, there are only some of the images for dark elixir storages for levels 1 to 4.  Look in the "Storages" folder, and you can see how many varieties of DE storages exist, depending on how full they are.  If you want to capture those images, I'm happy to include them.

**Comment by Stormtrail** [comment]
Thanks for that Code, are there any special rules or recommendations for resolution/size/format for captured images?

**Comment by CodeSlinger69** [comment]
Grab me a Windows .bmp formatted image, along with the % fill of that storage, and I'll do the rest.  I have the bot's files in a specific size and position so as to inform the eligible click location, but if you can capture the image, I can do the rest.

**Comment by chrishubert** [comment]
I guess this issue is irrelevant now after the July 1st update

**Comment by CodeSlinger69** [comment]
Yup.  Sad that we lost this ability, but the game changes and we move on.  Closing.
