### ISSUE TITLE
BlueStacks being wrong size causes a $gDebug variable undefined error

### ISSUE THREAD

**Issue by deanhill1971** [CodeSlinger69/ClAsHbOt#17]
I just tried Clashbot v20150623. The bot looks great, but I got the following error message boxes.

From looking at the code, when the BlueStacks resolution is wrong, FixBlueStacksSize() is called. This function then calls DebugWrite which causes the $gDebug error.

To resolve the problem I created $gDebug in Globals.au3.
Is there a reason this variable isn't already in Globals (with a default value of 0/false)?

![clashboterror1](https://cloud.githubusercontent.com/assets/13065360/8378860/474926b6-1bea-11e5-8b8c-382634b95a48.png)
![clashboterror2](https://cloud.githubusercontent.com/assets/13065360/8378865/4be438fa-1bea-11e5-9b16-11db054ab77d.png)

**Comment by CodeSlinger69** [comment]
It was originally being created and set in Globals.au3, but is now being created and set in Settings.au3, as part of a refactoring a while back.  I've fixed this, as this variable could be needed (as you've discovered) prior to ReadSettings() being called.

Thanks.

Commit: https://github.com/CodeSlinger69/ClAsHbOt/commit/65e83e88e7689ddcd77dd303e2545e837273cc8e

Will leave this issue open until next release.

**Comment by CodeSlinger69** [comment]
Included in this release: https://github.com/CodeSlinger69/ClAsHbOt/releases/tag/20150707
