### ISSUE TITLE
During Auto Raid, "Find a Match" button can't be found

### ISSUE THREAD

**Issue by deanhill1971** [CodeSlinger69/ClAsHbOt#18]
I'm using Clashbot v20150623.

When doing Auto Raid, building troops works fine. The Attack button is clicked, but then the script hangs trying to locate the "Find a Match" button.
Attached is a screen shot of my Find a Match screen.

I see in RegionDefs.au3 where $rFindMatchScreenFindAMatchButton is looking for the button. Looking at my screen shot, it seems like my Find a Match button is lower than the coordinates Clashbot is looking for. I'm not sure why my screen would be different.

Here is my Clashbot log. I haven't had time yet, but I'll try changing the coordinates in RegionDefs to see if I can move forward. I have yet to get Clashbot to work, but love that it is open source AutoIt. Thanks for all your hard work.

===== Start of Log =====
6/25/2015 10:26:55 PM Keep Online clicked
6/25/2015 10:27:01 PM Collect Loot clicked
6/25/2015 10:27:09 PM CollectLoot()
6/25/2015 10:30:16 PM CollectLoot()
6/25/2015 10:33:10 PM Auto Raid clicked
6/25/2015 10:33:15 PM Auto Begin:  Gold:2611357 Elix:5861960 Dark:8366 Cups:1590
6/25/2015 10:33:23 PM CollectLoot()
6/25/2015 10:33:26 PM AutoQueueTroops()
6/25/2015 10:33:27 PM OpenArmyCampWindow()
6/25/2015 10:33:28 PM Located Level 7 Army Camp at 296, 423 confidence 98.31%
6/25/2015 10:33:30 PM FindArmyCampTroopSlots()
6/25/2015 10:33:31 PM Troop Barbarian available: 49
6/25/2015 10:33:31 PM Troop Archer available: 55
6/25/2015 10:33:31 PM Troop Giant available: 4
6/25/2015 10:33:31 PM Troop Wall Breaker available: 4
6/25/2015 10:33:31 PM Troop Wizard available: 7
6/25/2015 10:33:36 PM OpenBarracksWindow()
6/25/2015 10:33:38 PM Barracks 0 found at 287,166 confidence 99.06%
6/25/2015 10:33:39 PM Train Troops button found at 362,7 confidence 99.92%
6/25/2015 10:33:42 PM FindSpellsQueueingWindow()
6/25/2015 10:33:58 PM Spells queued: 2 of 4
6/25/2015 10:33:59 PM FillBarracksStrategy0(), initial fill.
6/25/2015 10:34:02 PM FillBarracksWithTroops(), Adding 74 Archer
6/25/2015 10:34:11 PM FillBarracksWithTroops(), Adding 75 Barbarian
6/25/2015 10:34:20 PM FillBarracksWithTroops(), Adding 75 Archer
6/25/2015 10:34:28 PM FillBarracksWithTroops(), Adding 75 Barbarian
6/25/2015 10:34:33 PM CloseBarracksWindow()
6/25/2015 10:36:32 PM CollectLoot()
6/25/2015 10:37:38 PM AutoCheckIfTroopsReady()
6/25/2015 10:37:39 PM OpenArmyCampWindow()
6/25/2015 10:37:40 PM Located Level 7 Army Camp at 453, 53 confidence 96.26%
6/25/2015 10:37:42 PM FindArmyCampTroopSlots()
6/25/2015 10:37:42 PM Troop Barbarian available: 56
6/25/2015 10:37:43 PM Troop Archer available: 59
6/25/2015 10:37:43 PM Troop Giant available: 4
6/25/2015 10:37:43 PM Troop Wall Breaker available: 4
6/25/2015 10:37:43 PM Troop Wizard available: 7
6/25/2015 10:37:48 PM OpenBarracksWindow()
6/25/2015 10:37:50 PM Barracks 0 found at 287,166 confidence 99.05%
6/25/2015 10:37:51 PM Train Troops button found at 362,7 confidence 99.92%
6/25/2015 10:37:52 PM FindSpellsQueueingWindow()
6/25/2015 10:38:08 PM Spells queued: 4 of 4
6/25/2015 10:38:08 PM FillBarracksStrategy0(), top up.
6/25/2015 10:38:12 PM FillBarracksWithTroops(), Adding 3 Archer
6/25/2015 10:38:19 PM FillBarracksWithTroops(), Adding 2 Barbarian
6/25/2015 10:38:26 PM FillBarracksWithTroops(), Adding 2 Archer
6/25/2015 10:38:33 PM FillBarracksWithTroops(), Adding 2 Barbarian
6/25/2015 10:38:36 PM CloseBarracksWindow()
6/25/2015 10:38:42 PM FindAValidMatch()
6/25/2015 10:38:53 PM Find Match failed - timeout waiting for Find a Match button
6/25/2015 10:38:54 PM Auto: Error finding match, resetting.
6/25/2015 10:39:02 PM AutoQueueTroops()
6/25/2015 10:39:03 PM AutoQueueTroops(): Not on main screen, resetting.
6/25/2015 10:39:15 PM AutoQueueTroops()
6/25/2015 10:39:16 PM AutoQueueTroops(): Not on main screen, resetting.
6/25/2015 10:39:27 PM AutoQueueTroops()
6/25/2015 10:39:28 PM AutoQueueTroops(): Not on main screen, resetting.
6/25/2015 10:39:41 PM AutoQueueTroops()
6/25/2015 10:39:43 PM AutoQueueTroops(): Not on main screen, resetting.
6/25/2015 10:39:57 PM AutoQueueTroops()
6/25/2015 10:39:59 PM AutoQueueTroops(): Not on main screen, resetting.
6/25/2015 10:40:14 PM AutoQueueTroops()
6/25/2015 10:40:16 PM AutoQueueTroops(): Not on main screen, resetting.
6/25/2015 10:40:32 PM AutoQueueTroops()
6/25/2015 10:40:34 PM AutoQueueTroops(): Not on main screen, resetting.
6/25/2015 10:40:49 PM AutoQueueTroops()
6/25/2015 10:40:51 PM AutoQueueTroops(): Not on main screen, resetting.
6/25/2015 10:41:06 PM AutoQueueTroops()
6/25/2015 10:41:08 PM AutoQueueTroops(): Not on main screen, resetting.
===== End of Log =====

![clashbotfindamatch](https://cloud.githubusercontent.com/assets/13065360/8379003/13e759d6-1beb-11e5-8e21-927b779e94ae.png)

**Comment by CodeSlinger69** [comment]
I hope this is not yet another pixel color variation problem, but I fear that it may be.  As a bit of history, there have been a few other issues related to varying rendering of pixel colors, even though we are all using the same BlueStacks version.  Very annoying.

You are correct that $rFindMatchScreenFindAMatchButton holds the specifications for that "Find a Match" button.  Specifically, the color at client location 108, 444 should be 0xD54400.  Buttons typically do not have much variance in color, which is why the radius (or error/variance) parameter for this button is set to zero.

Keep in mind that all locations are client oriented, so if you are using the AutoIt Window Info utility, set Options/Coord Mode to "Client".

Alternatively, go to line 97 in AutoRaid.au3, and make the code block look like this:

```
   If $failCount = 0 Then
      Local $cPos = GetClientPos()
      Local $color = PixelGetColor($cPos[0]+$rFindMatchScreenFindAMatchButton[4], $cPos[1]+$rFindMatchScreenFindAMatchButton[5])
      DebugWrite("Find Match failed - timeout waiting for Find a Match button, color = " & Hex($color))
      ResetToCoCMainScreen()
      Return False
   EndIf
```

That way, the debug log will show the color that is actually being seen at that location.

I have several ways to fix this problem, if you are indeed seeing different colors from what I have coded for that button.  Let me know what color you are seeing, and we'll figure out how to fix it.

**Comment by deanhill1971** [comment]
I was without electricity for a couple days and just got around to this issue again.

With your debug code, the reported color is 0xD64400. RegionDefs.au3 uses 0xD54400 by default. Once I changed RegionDefs, Auto Raid started working.

However I think the root problem might be looking for the color in the wrong location. I say this because there are couple times Clashbot failed to properly report my Gem count (it was reported as zero instead of 351), Cup count (reported as 15 instead of 1586), and Net Winnings (reported as my current values instead of the net values). However, after running a couple Auto Raid Clashbot managed to get the correct values for all these fields.

What's a simple way to see if my coordinates match up with what Clashbot expects?

**Comment by CodeSlinger69** [comment]
So indeed, it is variations of color.  Annoying problem.  I'll fix this with image recognition, as I mentioned.  Once I do that, the coordinates problem goes away.  This is lower priority than the bot-breaking changes that just came out in the July 1 update, by the way, but I'll get to it.

However, there is really no easy way to see in the coordinates match up, other than to use the "AutoIt Window Info" tool, and see what the color is at a given location.  That's the tool I used as I was programming the bot, for what it's worth.

**Comment by CodeSlinger69** [comment]
Going to leave this as a pixel color match for now.  Might expand the "radius" parameter of the color region if needed, but I don't see a need to go to image matching for this button at the moment.
