### ISSUE TITLE
Scraper.au3 error. Subscript used on non-accessible variable

### ISSUE THREAD

**Issue by deanhill1971** [CodeSlinger69/ClAsHbOt#20]
After Clashbot ran for about 16 hours I closed the Clashbot window and got the below error.
It's not a big deal since it happened at shutdown. Just wanted to make you aware of it.

![scrapererror](https://cloud.githubusercontent.com/assets/13065360/8457443/576c8f1c-1fdf-11e5-8e88-162364e46f9a.jpg)

**Comment by Stormtrail** [comment]
I had the same issue Dean, been trying to replicate it and get Code some screenshots. I don't think anything makes it to the debug log so he's flying blind.

**Comment by deanhill1971** [comment]
I checked the log also, and no info there.

I just spent some time with the code, and found the problem.
Below is the full function.
$gTitle is the name of the BlueStacks window. If the window has been closed (which I must have done), then WinGetHandle() and WinGetClientSize() will both fail. Their return values ($hWnd and $cSize) won't be valid and the @error flag is set.

So @error needs to be checked after the WinGetHandle() and WinGetClientSize() calls.
GetClientPos() is called from many places so I'm not sure what it should return during this error condition.

``` autoit
Func GetClientPos()
   Local $cPos[4]

   ; Get absolute coordinates of client area
   Local $hWnd = WinGetHandle($gTitle)
   Local $cSize = WinGetClientSize($gTitle)

   Local $tPoint = DllStructCreate("int X;int Y")
   DllStructSetData($tPoint, "X", 0)
   DllStructSetData($tPoint, "Y", 0)

   _WinAPI_ClientToScreen($hWnd, $tPoint)
   $cPos[0] = DllStructGetData($tPoint, "X")
   $cPos[1] = DllStructGetData($tPoint, "Y")
   $cPos[2] = $cPos[0]+$cSize[0]-1
   $cPos[3] = $cPos[1]+$cSize[1]-1

   Return $cPos
EndFunc
```

**Comment by CodeSlinger69** [comment]
You are both right, I should be checking @error in this function.

If I understand what you are saying, this error occurs when you shutdown BlueStacks, prior to shutting down ClashBot, right?

I'm neck deep in July 1 update changes at the moment, so I'll address this issue at a later point.  Even if shutting down BlueStacks first, ClashBot should handle this more gracefully.

**Comment by deanhill1971** [comment]
Yes, this will only happen if BlueStacks is shutdown before ClashBot.
So the workaround is to close ClashBot first.

**Comment by Stormtrail** [comment]
It's a minor issue, but for me this error occasionally cropped up with blue stacks open on a different pc at startup of the bot. I'll keep trying to replicate and/or find the error but this particular case was not what was causing the same error for me.

I'll just echo Dean in that if you do want more assistance in any way I'm willing and able to do my part to help. If not, we appreciate your efforts!

**Comment by CodeSlinger69** [comment]
Fixed: https://github.com/CodeSlinger69/ClAsHbOt/commit/dae1ceabd3dbdfeda21b98b457b4fc1f0b81373e

Will keep this issue open until the next official release.

**Comment by CodeSlinger69** [comment]
Released: https://github.com/CodeSlinger69/ClAsHbOt/releases/tag/20150723
