### ISSUE TITLE
Option to end raid early

### ISSUE THREAD

**Issue by CodeSlinger69** [CodeSlinger69/ClAsHbOt#26]
Idea from Cydin in open discussion thread:

"i think maybe u can make like gamebot they use timer that we can input, if no resource change between X seconds then end battle even the troops or BK/AQ not finished they attack"

Implementation will be as an option in the .ini file, to specify when an attack should be ended, after the available resource counters stop changing, regardless of troop/hero deployment status. If zero, then the standard logic will apply.  Entry will default to zero for backwards compatibility reasons.

**Comment by cydin** [comment]
thanks @CodeSlinger69 for making this, may GOD bless u, this can become more handy and much faster raid

**Comment by CodeSlinger69** [comment]
You do realize that this will not help the speed of farming at all?  While you are waiting for the 1 minute or so for the raid to end, your queued up troops are still building.   Whether you end the raid now or one minute from now, you still need to wait for those troops.

What this will do, however, and the reason I agreed to it, is to make it appear just a bit more human-like.  Thus less probability to be detected as a bot.

**Comment by CodeSlinger69** [comment]
Commit: https://github.com/CodeSlinger69/ClAsHbOt/commit/b7a2b2b528885676652a1851dc19d9fb150fe357

Seems to be working fine.  If you do nothing with this new setting in the .ini file, the bot will operate as before in regards to deciding when to end a raid.

**Comment by cydin** [comment]
wow, thanks again @CodeSlinger69 may GOD bless u, gonna try this

**Comment by CodeSlinger69** [comment]
Closing, as this is now in release: https://github.com/CodeSlinger69/ClAsHbOt/releases/tag/20151208
