### ISSUE TITLE
Scraping, OCR, Image Recognition

### ISSUE THREAD

**Issue by ddddddclash** [CodeSlinger69/ClAsHbOt#31]
This is another discussion thread not an issue!

The topic is programming as it specifically relates to computer vision, how they see things and how to write code to make them recognize what you want.
#### My first question is about the regions and how they are defined.

I want to learn how to use them and find out if they will fit my purpose without modification. I have been modifying quite a lot of things, mainly because I don't know how you intended them. Often I find out, after many revisions, that the original did what I needed, it was me that needed to change.

Here is your code.

```
; Text boxes - left, top, right, bottom, Text Color - center, radius,
; Present indicator x, y, color, radius
Global $rGoldTextBox[10] = [42, 57, 120, 74, 0xfffbcc, 9, 30, 66, 0xeace3f, 6]
```

left, top, right, bottom = screen coordinates of bounding rectangle.
Text Color at center and radius from center are self exploratory.

What is the Present indicator x,y and additional color and radius?
#### A second question is What are the numbers in the CharMaps?

"0" - is the character '0'
7  - is the quantity of numbers
... - The numbers but I don't know what they mean. They aren't in pairs so they aren't x,y cordinates as origianly suspected. 

Here is your code.

```
; Army Camp Troop Counts
Global $gArmyCampCharMapsMaxWidth = 8
Global $gArmyCampCharacterMaps[10][$gArmyCampCharMapsMaxWidth+2] = [ _
 ["0", 7, 126, 127, 65, 65, 65, 127, 62], _
 (... more info not included) 
 ["9", 6, 112, 241, 137, 154, 254, 60] ]
```

**Comment by CodeSlinger69** [comment]
First question is easier, so I'll address that one first.  Some regions are only present at certain times on the game screen.  An example is the dark elixir bar - only when you get to TH7 and you build a dark elixir storage does this region start to exist.  

So in some cases, the presence of a region is checked prior to executing the appropriate logic for that region.  In our example of dark elixir, if you look at the GetMyLootNumbers() function in ClAsHbOt.au3, you'll see this line of code:

"If IsTextBoxPresent($rMyGemsTextBoxWithDE) = True Then..."

The IsTextBoxPresent function uses the Present Indicator elements in the region array to determine if the user has a dark elixir bar.  Only if this is the case, will the bot try to scrape the amount of "MyDark".  Like many other logical decisions in the bot, this is based on pixel location and color.  If the pixel color at the specified location is within the specified color sphere, then there is a match.

**Comment by CodeSlinger69** [comment]
Second question.  First element is the character that results on a match, and second element is the count of columns that make up the character.  Each following element is a binary representation of the foreground pixels in that column of the character. An example will help.

The first thing the algorithm does is to separate the foreground pixels from the background pixels.  That's the purpose of the center color and radius elements in the text box region definitions.  Here's an example result from that separation, this is "My Gold":

```
256 xxxxxx  xxxxx      xxx         xxxxx  xxxxxx     xxx
128 xxx        xx    xxxxxx       xxxxxx  xxx      xxxxxx
 64 xx         xx   xxx  xxx      xx   x  xx      xxx  xxx
 32 xx         x    xx   xxx      xx   x  xx      xx   xxx
 16 xxxxxx   xxxx   xx   xxx      xxxxxxx xxxxxx  xx   xxx
  8    xxx      xx  xx   xxx          xxx    xxx  xx   xxx
  4    xxx      xx  xx   xxx          xx     xxx  xx   xxx
  2   xxxx     xxx  xx   xxx         xxx     xxx  xx   xxx
  1 xxx     xxxx     xxxxxx        xx     xxx      xxxxxx
```

The algorithm then builds up binary representations of each column - I've overlaid the binary values on the left in the pixelmap above.  For the first "5", the first column is 1+16+32+64+128+256=497.  The values for the remaining 5 columns in the first character are similarly: 497, 403, 286, 286 and 286.

The algorithm then next finds the closest match of those 6 column values in the character maps array, in this case it scans through $gSmallCharacterMaps.  Note that there is a slight pixel difference between the two "5" characters above...this is inevitable due to the slight rendering differences in pixel colors at different times. To account for this, the algorithm looks for a closest match, using a weighted Hamming Distance calculation.

By the way, if you turn on scraper debug in the ini file, then run the bot in the AutoIt editor, you will see the foreground pixel maps, plus the column calculations in the AutoIt output window at the bottom.  Whenever something changes/breaks, I'll turn on that debug, look at the output and make the necessary adjustments.

HTH.

**Comment by ddddddclash** [comment]
- Knowing that they character maps are binary values of the pixels makes sense now. Thanks.
- The debug info tells me that this pattern is not a recognized character.  If i were to recognize the character I could simply create a new array element with the numbers shown. Is that correct?

```
Char start/end 8/16 of 133
TestWidth=9 ColValues=1, 1, 1, 2033, 2033, 2033, 1025, 1, 1, 
width=9 index=8 weight=1.53333333333333(bestweight=999)
8 to 6: `
```
- My earlier question about how to come up with Pixel patterns comes from CGB now mybot.
  Found in functions\Read Text\getChar.au3. It appears as though they use 3 colors for each letter. 

Relating to this I have some questions.
1.  Are you familiar with their method?
2.  If so why did you choose your method?
3.  Do you know which is faster and more accurate. You mention that the pixel colors change so I would be concerned about using a method that relies pixel colors.

For this version I am going to use your method, because I understand it now and can tweak it to do what I want, but more knowledge is good. Right? :)

**Comment by CodeSlinger69** [comment]
The unrecognized character:  can you post the X-output, like I did above?  I'd like to see what this looks like, as the string of one pixels on the bottom to the left and right are strange.

I'm familiar with the CGB project, but never looked deep into their code.  However, I am using three colors for each pixel as well, to separate the foreground from the background.  The magic in recognizing text from fuzzy character rendering is in this pixel separation step.  Think of the center color as a point in RGB space - and then a sphere in RGB space defined by this center point and then the specified radius.  Any pixel that falls within that sphere is designated as "foreground"..but this is where the artistry comes into play...defining that sphere to identify just the right amount of foreground pixels to ensure good character separation, but not too big of a sphere such that background pixel noise seeps in.  Its a bit of trial and error.

And yes, it is fast. The slowest part of the code by far is the image search routines.  The OCR stuff is very fast by comparison.

**Comment by ddddddclash** [comment]
I am not sure what that character was.  I have been playing around with it changing sizes, mixing $gRaidLootCharMaps, $gSmallCharacterMaps, $gLargeCharacterMaps, $gExtraLargeCharacterMaps and $gChatCharacterMaps. To see how they work.

That may have even been me forcing it to read on the wrong screen, something that is not even text.

I am trying to see if any of the Character Maps that you created work with the war data.  My question was more how to create new characters, and I just used an unknown result to form my question.

**Comment by ddddddclash** [comment]
So This one is better.  I set the color radius to 80 and this is what I come up with.
The problem is that it thinks the '/' is a '7'
I am using $gSmallCharacterMaps.

I want to add a new character.

```
11/20/2015 17:47:10 Char start/end 8/13 of 49
TestWidth=6 ColValues=198, 390, 273, 273, 306, 494, 
width=6 index=13 weight=0.4(bestweight=999)
8 to 13: 8
11/20/2015 17:47:10 Char start/end 16/22 of 49
TestWidth=7 ColValues=254, 511, 257, 257, 387, 510, 124, 
width=7 index=0 weight=0.351351351351351(bestweight=999)
16 to 22: 0
11/20/2015 17:47:10 Char start/end 24/28 of 49
TestWidth=5 ColValues=1, 7, 60, 240, 128, 
width=5 index=11 weight=0.769230769230769(bestweight=999)
24 to 28: 7
11/20/2015 17:47:10 Char start/end 31/36 of 49
TestWidth=6 ColValues=486, 483, 289, 273, 275, 286, 
width=6 index=10 weight=0.444444444444444(bestweight=999)
31 to 36: 6
11/20/2015 17:47:10 Char start/end 39/45 of 49
TestWidth=7 ColValues=254, 511, 257, 257, 387, 510, 124, 
width=7 index=0 weight=0.351351351351351(bestweight=999)
39 to 45: 0
11/20/2015 17:47:10 Char start/end -1/-1 of 49
80760
-------------------------------------------------------------------------
|         xxxxx   xxxxx     xx  xxxxxx   xxxxx     |
|        xx   x  xx  xx     x   xx      xx  xx     |
|        x    x  xx   xx   xx   xx      xx   xx    |
|            xx  xx   xx   xx   xxx     xx   xx    |
|          xxx   xx   xx   x       xxx  xx   xx    |
|             x  xx   xx  xx         x  xx   xx    |
|        xx   x  xx   xx  x     x    x  xx   xx    |
|        xx  xx  xx  xx  xx     xx  xx  xx  xx     |
|          xx     xxxx           xxxx    xxxx      |
-------------------------------------------------------------------------
```

Edit: As I look Closer it says 80760 and not the 30/50 as it should.  How can I tell if it is the right character map?

**Comment by CodeSlinger69** [comment]
Yeah, the first thing you need to do is find the right font set (character map), if one already exists.  I have not looked at the war stats font to see if it is similar to any of the others that I have already mapped.

The best thing to do is look at the height of the fonts.  This one looks to be 9 pixels in height, so I would look at other fonts (char maps) of similar height.  Bear in mind that if you use one of my existing char maps, you are going to need to set the center/radius in such a way that you generate similar foreground pixel separation, otherwise you will get match errors.

If either 1) the war stats fonts are different from the other fonts in the game, or 2) you are generating significantly different foreground separation, then it may make sense to create a new character map just for this purpose.

**Comment by ddddddclash** [comment]
Any Idea how to process the j separately.  It becomes 1 character and I think that means that I need an extra character for each combination.  look at the tj combination. so I would need 26*2 extra letters if I do the combination method.  There has to be something better, but all solutions look like they would require modification to your scarper algorithm. 

1 idea define a base line. It would also help with a . vs a - both are ".",3,3,3,3 and "-",3,3,3,3
2 fuzzy definition of a line between characters. I have no idea how to do this one though.

```
11/26/2015 19:33:25 Char start/end 9/18 of 156
TestWidth=10 ColValues=798, 4095, 4095, 3171, 3171, 3171, 4095, 4095, 1854, 28, 
|10|798|4095|4095|3171|3171|3171|4095|4095|1854|28
Best 15 0.2
width=10 index=15 weight=0.2(bestweight=999)
9 to 18: 6

11/26/2015 19:33:25 Char start/end 20/22 of 156
TestWidth=3 ColValues=1, 3, 3, 
|3|1|3|3
Best 0 0.2
width=3 index=0 weight=0.2(bestweight=999)
20 to 22: .

11/26/2015 19:33:25 Char start/end 31/39 of 156
TestWidth=9 ColValues=511, 511, 511, 280, 280, 286, 511, 511, 243, 
|9|511|511|511|280|280|286|511|511|243
Best 12 0
width=9 index=12 weight=0(bestweight=999)
31 to 39: r

11/26/2015 19:33:25 Char start/end 43/51 of 156
TestWidth=9 ColValues=254, 511, 511, 387, 387, 387, 511, 511, 254, 
|9|254|511|511|387|387|387|511|511|254
Best 8 0
width=9 index=8 weight=0(bestweight=999)
43 to 51: o

11/26/2015 19:33:25 Char start/end 54/63 of 156
TestWidth=10 ColValues=2047, 4095, 4095, 195, 195, 195, 255, 254, 126, 56, 
|10|2047|4095|4095|195|195|195|255|254|126|56
Best 37 0.0140845070422535
width=10 index=37 weight=0.0140845070422535(bestweight=999)
54 to 63: b

11/26/2015 19:33:25 Char start/end 66/74 of 156
TestWidth=9 ColValues=254, 510, 510, 403, 403, 275, 499, 499, 496, 
|9|254|510|510|403|403|275|499|499|496
Best 20 0
width=9 index=20 weight=0(bestweight=999)
66 to 74: e

11/26/2015 19:33:25 Char start/end 77/85 of 156
TestWidth=9 ColValues=511, 511, 511, 280, 280, 286, 511, 511, 243, 
|9|511|511|511|280|280|286|511|511|243
Best 12 0
width=9 index=12 weight=0(bestweight=999)
77 to 85: r

11/26/2015 19:33:25 Char start/end 89/101 of 156
TestWidth=13 ColValues=768, 768, 8188, 16380, 16380, 16128, 512, 513, 513, 3, 10239, 26623, 26622, 
|13|768|768|8188|16380|16380|16128|512|513|513|3|10239|26623|26622
Best 45 0
width=13 index=45 weight=0(bestweight=999)
89 to 101: tj

11/26/2015 19:33:26 Char start/end 104/112 of 156
TestWidth=9 ColValues=4095, 4095, 4095, 56, 120, 254, 511, 455, 257, 
|9|4095|4095|4095|56|120|254|511|455|257
Best 40 0
width=9 index=40 weight=0(bestweight=999)
104 to 112: k

11/26/2015 19:33:26 Char start/end 115/118 of 156
TestWidth=4 ColValues=1024, 2047, 4095, 4094, 
|4|1024|2047|4095|4094
Best 1 0
width=4 index=1 weight=0(bestweight=999)
115 to 118: 1

11/26/2015 19:33:26 Char start/end 122/129 of 156
TestWidth=8 ColValues=1055, 3135, 3135, 3191, 3299, 4067, 4035, 1922, 
|8|1055|3135|3135|3191|3299|4067|4035|1922
Best 39 0
width=8 index=39 weight=0(bestweight=999)
122 to 129: 2

11/26/2015 19:33:26 Char start/end 132/139 of 156
TestWidth=8 ColValues=1027, 3075, 3171, 3171, 3815, 4095, 4030, 1854, 
|8|1027|3075|3171|3171|3815|4095|4030|1854
Best 2 0
width=8 index=2 weight=0(bestweight=999)
132 to 139: 3

11/26/2015 19:33:26 Char start/end -1/-1 of 156
6.robertjk123
-------------------------------------------------------------------------
|                                                                                                    xx                                                       |
|          xxxxxxx                                      xx                                   xxx    xxx  xxx          xx    xxxxxx    xxxxxx                  |
|          xxxxxxxx                                    xxx                                  xxxx         xxx        xxxx   xxxxxxxx  xxxxxxxx                 |
|         xxx   xxx                                    xxx                                  xxxx         xxx         xxx        xxx      xxxx                 |
|         xxx   xxx             xxxxxxxx     xxxxxxx   xxx          xxxxxxxx  xxxxxxxx      xxxx    xxx  xxx   xxx   xxx        xxx       xxx                 |
|          xx   xx              xxx   xxx   xxxxxxxxx  xxxxxxxx    xxxxx xxx  xxx   xxx   xxxxxxxxx xxx  xxx  xxx    xxx       xxxx      xxx                  |
|          xxxxxxx              xxx   xxx   xxx   xxx  xxxxxxxxx   xxx   xxx  xxx   xxx   xxxxxx    xxx  xxx xxxx    xxx      xxxx     xxxx                   |
|          xxxxxxxx             xxx   xxx   xxx   xxx  xxx   xxxx  xxx   xxx  xxx   xxx     xxx     xxx  xxxxxxx     xxx    xxxxx      xxxxxx                 |
|         xxx   xxxx            xxxxxxxxx   xxx   xxx  xxx   xxxx  xxxxxxxxx  xxxxxxxxx     xxx     xxx  xxxxxxx     xxx   xxxx           xxx                 |
|         xxx   xxxx            xxxxxxxx    xxx   xxx  xxx   xxxx  xxx        xxxxxxxx      xxx     xxx  xxxxxxx     xxx   xxx            xxx                 |
|         xxx   xxxx            xxx  xxx    xxx   xxx  xxx   xxx   xxx        xxx  xxx      xxx     xxx  xxx  xxx    xxx   xxxx          xxxx                 |
|         xxxxxxxxx   xx        xxx  xxxx   xxxxxxxxx  xxxxxxxxx   xxxxxxxx   xxx  xxxx     xxx     xxx  xxx  xxx    xxx   xxxxxxxx  xxxxxxxx                 |
|          xxxxxxx   xxx        xxx   xxx    xxxxxxx   xxxxxxx        xxxxx   xxx   xxx     xxx     xxx  xxx   xxx   xx    xxxxxxx   xxxxxx                   |
|                                                                                                  xxxx                                                       |
|                                                                                                xxxxx                                                        |
-------------------------------------------------------------------------
```

**Comment by CodeSlinger69** [comment]
Yup, that kind of character situation is always a problem.  When defining the color center/radius, you want to be careful to get enough foreground pixels to define characters, but also to ensure that there is no overlap between characters.  In some cases you have no choice but to define characters for the "combined" pixel group.  You might have noticed that I had to do that for the "74" group in a couple of places, as I could just not get good separation when those characters were together.

If you can define color in such a way that you get a nice clean background column between characters, that is best.  If not, then the next best is to do what you say, and define the combined characters.  Not optimal, but any other solution is going to require a radical code change.

But by all means, if you come up with a better algorithm, I am happy to hear about it!

**Comment by CodeSlinger69** [comment]
Closing to due inactivity.
