### ISSUE TITLE
Wait for Hero check box

### ISSUE THREAD

**Issue by jjoocc** [CodeSlinger69/ClAsHbOt#33]
It would be great with a "Wait for Hero" check box. 
So no attacks starts without atleast one Hero available.
/JoC

**Comment by CodeSlinger69** [comment]
Initial implementation in this commit: https://github.com/CodeSlinger69/ClAsHbOt/commit/28a60a0e839115d6e587b6482a2edda24bd27bd9

**Comment by CodeSlinger69** [comment]
Released: https://github.com/CodeSlinger69/ClAsHbOt/releases/tag/20160118
