### ISSUE TITLE
IMPORTANT: Do not take optional update

### ISSUE THREAD

**Issue by CodeSlinger69** [CodeSlinger69/ClAsHbOt#40]
DO NOT TAKE OPTIONAL WINTER UPDATE

Folks,  I am traveling on a family vacation and will not be working on the bot during this time.  There is now an "Optional" winter update that among other things, allows you to disable the falling snow.  However, it does add snow on the buildings.

Snow on the buildings will require me to capture new images for storages, collectors and town hall, at a minimum. I am loathe to do this at the best of times, but given that I just finished doing this for the Dec 10 update, I am really loathe to do it again, even if I was not traveling.

The bot appears to be working fairly well, and is even making loot for me on my TH10 account.  Given the lack of problems at this time, I'll leave the code base alone for now, and look at it again when I get back.  There are a few minor things left to do on the Dec 10 update, but nothing bot-killing.

**Comment by CodeSlinger69** [comment]
I found some time to capture the required snow covered building images.  Far less work than I expected.  Feel free to take the optional update now.

https://github.com/CodeSlinger69/ClAsHbOt/commit/e1bfea86c4e7d01d5a18c3635f1edbc45dac9db9

**Comment by Stormtrail** [comment]
Code, is there a particular sequence of steps or tool set that you use to get images the right way for clashbot? I know it would take some time possibly, but describing what you're looking for and how you achieve them might free you up down the road when special events happen and your willing crowd sources the images for you.

Not sure how long it would take to toss up a fast "this is what is key for making useful bit maps" tutorial.

**Comment by CodeSlinger69** [comment]
It's really easy.  I just use IrfanView to capture a screen shot, then crop as needed.  I use Irfan because it is free, I have used it for a long time, and I am very familiar with it, but any kind of screenshotting tool could work.

The only challenge is finding the right images, and cropping them to the right size.  But, one could easily look though the other little image clips to understand what I have found to be the best size for each type of image.

**Comment by Stormtrail** [comment]
Yeah I figured the proportion and size were basic, wasn't sure if there were specific orientation points for the images. As in "always start the image from the such and such pixel of the structure". From the sounds of it, that's a no :)

Anyway, thanks for the updates and have a merry Xmas!

**Comment by CodeSlinger69** [comment]
You are correct, there is no general rule for orientation points and such.  Generally what I try to do is to capture 1) the smallest part of an image that can be used to uniquely identify the image, and 2) the part of the image that is least likely to be obscured by other game elements.  It's more art than science :)

Merry xmas to you too!
