### ISSUE TITLE
Interaction improvements - window capture / mousing

### ISSUE THREAD

**Issue by CodeSlinger69** [CodeSlinger69/ClAsHbOt#43]
My current efforts are to make the bot work in such a way as the bluestacks window can be obscured/minimized, and that you can continue to do other work on the computer without the mouse being stolen.

There are two parts to make this work:
1. Capture screenshot via Windows API calls rather than via the AutoIt built in functions.
   Status: This is working as of last night, and works for obscured, offscreen, and minimized windows.
2. Use ControlClick, rather than MouseClick to interact with the BlueStacks window.  This also requires using ControlSend to send keystrokes (such as when zooming out).
  Status: ClAsHbOt has long had the ability to use ControlClick via a toggle in the .ini file.  However, ControlSend is problematic in that sometimes it just doesn't work.  This is a well documented problem, but no one has a solution yet, other than using ControlSetText, which doesn't work with BlueStacks/CoC, unfortunately.
  Until I can get ControlSend or a replacement working, this feature is not quite ready for primetime.  I have even looked at other open source projects (e.g. mybot.run), and while they use ControlSend as well, it is wrapped in layers and layers of error handling/retry logic, just due to this problem.
  I could use the ADB bridge, but this is problematic as well, as the ADB bridge often fails and would require extensive error checking/handling to be effective.

Kind of stuck right now, but I am still hacking on this problem, as 1) I enjoy it 2) it bugs me and 3) I would like the bot to operate in this manner.

If anyone has any ideas on making ControlSend robust, please let me know.  Really, the only thing I need it for is zooming out, so zoom out alternatives are appreciated as well.

**Comment by CodeSlinger69** [comment]
I think I have #2 solved with _SendMessage.  Going to test for a few days.

Correction on #1 - this does not work on minimized windows.  I'm not sure that can be done within Windows API limitations.  Obscured and off screen does work, however, which meets my needs.

**Comment by CodeSlinger69** [comment]
This is working very well, so I decided to push it onto GitHub: https://github.com/CodeSlinger69/ClAsHbOt/commit/9eca9f63a6af1ba5c6754f0bf6119292243c7ba8

As part of enabling this new interaction model, I changed the BS window size again, as whether it fits on laptop sized screens is no longer relevant.  This brings other benefits as well:
- No more dragging, ever
- Better zoom control, as when fully zoomed out, there is a small row of black pixels on the top of the screen as an indicator

I had to recapture some images and fonts, but that was pretty fast.  If you try this build out, please let me know in this thread how it works.

Next up is to get rid of the temporary .bmp files that are created in the script directory. A long time ago, I used these for debugging, but that time is long past, and that code should be cleaned up.

**Comment by CodeSlinger69** [comment]
As an aside, the bot is much faster now.  Making it faster and less resource intensive is another objective of moving some time consuming logic to the DLL.  Other candidates for moving to the DLL includes the OCR algorithms in scraper.au3.  Besides the image search, OCR is the second most CPU intensive activity.

**Comment by chrishubert** [comment]
@CodeSlinger69 , that's awesome. The speed increase is really noticeable!
I've seen some glitches (non blocking), and try to reproduce them.

**Comment by CodeSlinger69** [comment]
Update: https://github.com/CodeSlinger69/ClAsHbOt/commit/8beab20eb789102cc6bfbb03d12798aa16750ffb

This alternate interaction approach is working great, but with a couple of caveats:
1. I was spamming BlueStacks with far too many "Print Screen" requests, and often it would end up lagging.  Print Screen is the way to get this obscured screen capture working correctly.  I've revised the code to be more more judicious when deciding to request a new frame, and the lag problem is resolve.
2. For reasons unknown to me at this time, this background/obscured image capture method ("Print Screen") does not work when BlueStacks is running in another Virtual Machine.  I have BS in two different VMWare VMs in order to easily run two CoC accounts.  I now detect when the background capture is not going to work, and fall back to the foreground approach; a warning Message Box is displayed as well.

**Comment by CodeSlinger69** [comment]
Commit: https://github.com/CodeSlinger69/ClAsHbOt/commit/31a559f767f98d16042dc5faac8f42be9bf570e4

Continued optimization.  Saving of screen shots for debugging purposes can be enabled in the .ini file.

**Comment by CodeSlinger69** [comment]
Commit: https://github.com/CodeSlinger69/ClAsHbOt/commit/5e70d09e5bd3dcb401fa06cc6a1f76ae6e3a647a

Starting to move code to the DLL, and optimize the scraping for performance.  I put in some instrumentation to test how long it takes to scrape various bits, and i have seen a 6 fold improvement in some areas with some basic changes.  This is especially important if you run BS in a VM, like I do sometimes.

More to come.

**Comment by CodeSlinger69** [comment]
Will continue to optimize over time, but as of now performance is acceptable to me.  I'll close this issue once I push an official release in a few days.

**Comment by dedren** [comment]
I am not having any success with this new commit version. Unless I am physically using the computer. When I don't use the computer for a while it just doesn't seem to fight or win any fights. Sometimes when I come back to check it out it will be on the Supercell for parents page in the Android browser (http://supercell.com/en/parents/). I have attached a picture.

It usually doesn't crash (just the once in the attached picture). As far as I can tell it just sits there until I remote into my machine then it starts back. Is there a way I could get the logs to share with you?

![screenshot_20160128-074838-2](https://cloud.githubusercontent.com/assets/16905451/12657293/a365d594-c5d0-11e5-8194-fd448cc1729b.jpg)

**Comment by CodeSlinger69** [comment]
Weird.  I will admit, that the bot is going though a bit of a stabilization phase right now.  I'm making lots of changes (12/10 update, 1/26 update, interaction mode, performance optimization, etc).  Weird behavior is not wholly unexpected.

That said, you mentioned you are running over RDP somehow?  On a hosted VM?  Or are you just checking in on your home machine while at work or something like that?  Does the display power off ("TUrn screen off after 10 minutes")?  This has bit me in the butt once before.

I have noticed that the background interaction mode does not work in a VM yet, and you might have the same problem with RDP.  The bot should warn about this, but you can also try forcing foreground mode.  In the .ini file, set "Use Background Mode=False".  I just added this ini option in the last day or two, so sync if you don't see it.  This will force the bot to scrape and click on the screen the old way - the BS window will need to not be covered/obscured.

Other than that, see if you can watch the bot and determine what is triggering this.   Take a look at the log and see if anything jump out at you, and paste the relevant parts here.

**Comment by dedren** [comment]
I am checking in on my home machine while at work. I use either the Google Remote Desktop app or Teamviewer (both bring the bot back to life when I connect). Yes, the screen definitely needs to turn off as I don't want my kids messing with my machine.

I'll try out that setting in the ini file after some more testing with screen on. I have two monitors and one running the bot and the other I was using to play a game for three hours and the bot had no issues then, so I think that sounds a lot like the problem you describe.

**Comment by CodeSlinger69** [comment]
Given the issues with this feature lately, I've decided to make foreground mode (the old way) the default.  Background mode now needs to be explicitly chosen via a checkbox on the GUI.  https://github.com/CodeSlinger69/ClAsHbOt/commit/f20ee9111d4bf8dd18a5bfa2afccdf8d12410c02

Once the box is ticked, a test will be run to make sure that the background mode will work correctly, and will notify if there are problems.

Once this goes to official release, I'll update the wiki accordingly.

**Comment by CodeSlinger69** [comment]
Released: https://github.com/CodeSlinger69/ClAsHbOt/releases/tag/20160201
