### ISSUE TITLE
January 26, 2015 Update

### ISSUE THREAD

**Issue by CodeSlinger69** [CodeSlinger69/ClAsHbOt#44]
New update affects the bot:
1. ~~Loot cart; need to automatically collect this when it appears.~~
2. ~~BlueStacks now has a transparent Android bar (not sure what it is actually called) that overlays the game when it is running.~~
3. ~~Snow is gone.  Need to update some images.~~
4. ~~Star Bonus popup window.~~
5. ~~Two different style Attack! buttons, depending if you have achieved the star bonus or not.~~

(2) Thoughts on the new Android bar overlaying the game:
- This changes the resolution of the game, and messes up a bunch of stuff.  I am going to experiment with just making the BlueStacks window a bit smaller in the vertical direction to adapt to this change.
- If anyone knows of a BlueStacks setting to disable this behavior, please let me know.  I am on version 0.10.7.5601 of BS, by the way.
- Strange, but this does not happen on my other physical devices.  My LG G3 phone and my Kindle Fire do not show the transparent Android bar on top of the game.
- Addressed this by reducing the BS height by 47 pixels, the size of the Android bar. Some minor region definition changes are needed as well, these are underway.

**Comment by CodeSlinger69** [comment]
I tried reverting back to an older trusted version of BlueStacks, 0.9.6.  Still has the transparent Android bar overlay.   Indicates to me that SuperCell changed something in their game.

**Comment by Stormtrail** [comment]
Code, while you're making these changes, would you be willing to consider adding defensive restocking to the bot? I know you're not keen to add CC requests, but I do think clearing up tombstones and refilling defensive towers from the TH are valuable features.

**Comment by CodeSlinger69** [comment]
Its a good idea, Storm.  I'm kind of getting tired of clicking on the restocking buttons myself.  Make a new issue for me please, and I'll get to it once I finish adapting to this update.

**Comment by rumbla** [comment]
What about change the registry key "SoftControlBar" to 0?
I have no preBS2 installed, so I cannot check, but that should make the SoftControlBar disappear.

I think in preBS2 version you can also modify the height of such bar.
The settings are all there, but I'm not sure if they're actually used.

An alternative might be install an app like Full!Screen. That should get rid of the SoftControlBar right away.

Last suggestion (that should work on most of the REAL devices, but didn't do much for me, with BlueStacks) is to add the following setting to /system/build.prop

```
qemu.hw.mainkeys=1  (or was it 0? can't remember really!)
```

**Comment by dedren** [comment]
Concerning the Android bar. It may have something to do with the older version of Android that BlueStacks uses and maybe Android changed how apps go full screen because it doesn't show up on my Android 5 tablet or Android 6 phone.

Maybe just forcing the app full-screen, like rumbla suggest might work.

**Comment by rumbla** [comment]
Full!screen is an app you need to install (from GooglePlay) and deals with the SoftControlBar and the Notification bar on-top.

https://play.google.com/store/apps/details?id=de.tsorn.FullScreen

It hides these "default" bars and adds two buttons on the lower corners (more if you want!)

There are other apps doing the same, btw.
Full!screen is just the one I personally use with BS2 to have a "back" button.
BS2 infact hides the SoftControlBar at the bottom by default and as previously reported,. you can show it again changing some registry values.
Unfortunately I don't think these registry keys are present for BS1.

**Comment by CodeSlinger69** [comment]
Thanks for the suggestions, guys.  I tried modifying the SoftControlBarEnabled reg key, but it had no effect.  I'm not keen to make everyone install a new app either, just in the spirit of trying to keep things simple.  As a final reason, my "Defense Farm" requires the use of the back button to close CoC, so I really can't have it be completely gone anyway.  (I'm currently at 4836 defenses :) :) )

For now I've been able to work around this newly transparent/overlapping system bar by ensuring that the bot just doesn't click there.  Testing thoroughly now, and it appears to be fine.  I'll commit after a few more hours of testing.

**Comment by CodeSlinger69** [comment]
Commit: https://github.com/CodeSlinger69/ClAsHbOt/commit/31a559f767f98d16042dc5faac8f42be9bf570e4
Been running great for hours now.

**Comment by leepupu** [comment]
with commit above, got 

```
AutoRaidFindMatch() Find Match failed - timeout waiting for Find a Match button
```

if in shield, screenshot below, maybe is resolution problem, thanks!

UnknownFramexxxxx.bmp
![UnknownFramexxxxx.bmp](http://i.imgur.com/a0XMgws.png)

**Comment by rumbla** [comment]
Alright, from MyBot, these adb commands should do:

Hide SoftControlBar/NotificationBar:
`service call activity 42 s16 com.android.systemui`

Show SoftControlBar/NotificationBar:
`am startservice -n com.android.systemui/.SystemUIService`

These two commands, as far as I can understand them, will kill/start the SystemUIService.

**Comment by CodeSlinger69** [comment]
That's helpful Rumbla, thanks.  I'll look into it, given my workarounds, I'm not sure if I need to even worry about the soft bar any more.  It was not hard to work around - just make sure the bot is not clicking in that area...

**Comment by CodeSlinger69** [comment]
I'm going to call this complete.  I'll close this issue once I push an official release in a few days.

**Comment by CodeSlinger69** [comment]
Released: https://github.com/CodeSlinger69/ClAsHbOt/releases/tag/20160201
