### ISSUE TITLE
Minimize mouse stealing

### ISSUE THREAD

**Issue by CodeSlinger69** [CodeSlinger69/ClAsHbOt#5]
The bot currently takes over the computer it is running on, as it clicks on various elements of the playing field and operates the game.

[ClashGameBot](https://gamebot.org) has a nice approach to minimize this problem, using ControlClick with x, y parameters.  This should be fairly easy to incorporate into my bot.  Only thing to check is if the 0,0 offset with ControlClick is the same as the client area's 0,0 offset, since everything my bot does is keyed to the client 0,0 location.

Will test it out and incorporate if feasible.  Click speed might be a problem for troop deployment, as I have a custom function based on a direct call to the windows api mouse event in order to bypass the built-in autoit delays.  I believe that all other clicking can use the ControlClick approach, however.

**Comment by CodeSlinger69** [comment]
Implemented and working. Release: https://github.com/CodeSlinger69/ClAsHbOt/releases/tag/20150411

**Comment by Stormtrail** [comment]
This mostly works, I'm noticing it occasionally zooms in when running other programs with scaleable windows. Most recent example is while using a web browser with bot running and occasionally having it zoom in to max.
