### ISSUE TITLE
Add better error checking/logging to DLL

### ISSUE THREAD

**Issue by CodeSlinger69** [CodeSlinger69/ClAsHbOt#51]
Note to self, based on comment from dedren here: https://github.com/CodeSlinger69/ClAsHbOt/issues/22

**Comment by CodeSlinger69** [comment]
https://github.com/CodeSlinger69/ClAsHbOt/commit/402faaf57cb54a9cfae1a6a1f3d88b106ba24e83

In this commit I have done two things:
1. Removed BlockInputEx (https://www.autoitscript.com/forum/topic/87735-blockinputex-udf/), which is an AutoIt UDF that was supposed to prevent inadvertent mouse/keyboard input (such as when you are using the computer) from getting sent to the BS window and messing up the Bot.  I added this a few commits ago, as I thought it would be a good idea, however, after doing #2 below, I discovered that this UDF was causing AutoIt crashes when the computer was being used by a human - just the symptoms that you guys have been reporting.  Thus, it got the axe.
2. Compiled CrashRpt into the ClAsHbOt DLL.  (http://crashrpt.sourceforge.net/).  This is a nice open source tool that will catch crashes, generate a dump, and offer to email that dump to me.  You can also save the dump to your hard drive and then attach it to this forum if you prefer doing that over email.  There is nothing personal in the dump, just the internal state of the DLL that will let me diagnose and fix any crashes.

I hope the removal of BlockInputEx fixes a lot of the problems you all have been seeing.  Clearly, trusting that code and adding it in was a mistake.

**Comment by PhuriousGeorge** [comment]
Thanks, will give it a try!

**Comment by PhuriousGeorge** [comment]
Seems to work wonderfully. I usually crash about 4 times by now

**Comment by CodeSlinger69** [comment]
Released: https://github.com/CodeSlinger69/ClAsHbOt/releases/tag/20160215
