### ISSUE TITLE
Problem popping bubbles on some "stuck" collectors

### ISSUE THREAD

**Issue by CodeSlinger69** [CodeSlinger69/ClAsHbOt#52]
As discussed in the "Open Discussion" thread, sometimes the bot won't pop a certain loot bubble or two.  I've reproduced this and will investigate.

**Comment by CodeSlinger69** [comment]
Commit here: https://github.com/CodeSlinger69/ClAsHbOt/commit/8cbdf6b6e9c7e6ba43ad8220856b2af59204cda6

This fixed it for me.  Please post in this thread if you still have "stuck" loot bubbles, and if you can, attach screenshots.

**Comment by PhuriousGeorge** [comment]
attached a photo on the open thread. will try the new code and see if I still have issues

**Comment by PhuriousGeorge** [comment]
I think that may have done it

**Comment by chrishubert** [comment]
For me as well - sometimes it may not "pop" all the bubbles at once, but eventually after several tries it will.

**Comment by CodeSlinger69** [comment]
Released: https://github.com/CodeSlinger69/ClAsHbOt/releases/tag/20160215
