### ISSUE TITLE
ClAsHbOt keeps trying to deploy Barb King even after he has been deployed

### ISSUE THREAD

**Issue by opensourceguy123** [CodeSlinger69/ClAsHbOt#53]
I'm running the current master of the repo (include the 15-odd commits), and I notice that ClAsHbOt keeps trying to deploy the barb king, even after he has successfully been deployed, causing the red error message "Please select another troop".

PS: I absolutely love ClAsHbOt!

**Comment by chrishubert** [comment]
@opensourceguy123 , could you provide more details regarding the issue, following the guidelines? https://github.com/CodeSlinger69/ClAsHbOt/issues/50

**Comment by opensourceguy123** [comment]
whoops, sorry about that. Here's an image showing the problem and the config parameters I've used:

![image](https://cloud.githubusercontent.com/assets/17028765/13025982/2198e526-d1e5-11e5-9a81-4af156013441.png)
1. The problem is fairly easy to reproduce: simply use barch, and the problem arises if there's a barb king available.
2. The relevant portion of the log is as follows (please let me know if more of the log is required, I'm cutting it short because the log is quite big):

```
12-Feb-16 23:54:41 Army Camps full.
12-Feb-16 23:54:41 CloseArmyManagerWindow()
12-Feb-16 23:54:42 AutoRaidFindMatch() Click Attack button
12-Feb-16 23:54:43 AutoRaidFindMatch() Click Find a Match button
12-Feb-16 23:54:48 AutoRaidGetDisplayedLoot() 92696 / 22658 / 71 / 32 / 8 / True
12-Feb-16 23:54:48 CheckForRaidableBase() No match (loot)
12-Feb-16 23:54:50 AutoRaidFindMatch() Click Next button
12-Feb-16 23:54:55 AutoRaidGetDisplayedLoot() 80745 / 69223 / 537 / 14 / 7 / False
12-Feb-16 23:54:55 CheckForRaidableBase() Match!

12-Feb-16 23:54:55 AutoRaidExecuteRaidStrategy0()
12-Feb-16 23:54:57 AutoRaidStrategy0GetDirection() Collectors found top: 2, bottom: 10
12-Feb-16 23:54:57 AutoRaidStrategy0GetDirection() Attacking from Bot
12-Feb-16 23:54:57 Available Barbarians: 110
12-Feb-16 23:54:57 Avaliable Archers: 90
12-Feb-16 23:54:57 Deploying 60% of Barbarians (66)
12-Feb-16 23:54:57 DeployTroopsToSides()
12-Feb-16 23:55:02 Deploying 60% of Archers (54)
12-Feb-16 23:55:02 DeployTroopsToSides()
12-Feb-16 23:55:05 Deploying remaining Barbarians (44)
12-Feb-16 23:55:05 DeployTroopsToSides()
12-Feb-16 23:55:08 Continuing: 1 troops available.
12-Feb-16 23:55:09 Deploying remaining Archers (36)
12-Feb-16 23:55:09 DeployTroopsToSides()
12-Feb-16 23:55:13 Continuing: 32 troops available.
12-Feb-16 23:55:16 Finishing to safe boxes: 32 troops available.
12-Feb-16 23:55:16 DeployTroopsToSafeBoxes()
12-Feb-16 23:55:16 Deploying to left safe box: 16 troops.
12-Feb-16 23:55:17 Deploying to right safe box: 32 troops.
12-Feb-16 23:55:19 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:21 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:22 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:24 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:25 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:27 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:28 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:30 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:32 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:33 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:35 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:36 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:38 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:39 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:41 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:43 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:44 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:46 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:47 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:49 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:50 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:52 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:54 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:55 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:57 Deploying Barbarian King...failed, will retry
12-Feb-16 23:55:59 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:00 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:02 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:04 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:05 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:07 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:08 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:10 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:11 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:13 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:14 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:16 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:17 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:19 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:21 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:22 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:24 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:25 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:27 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:29 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:30 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:32 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:33 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:35 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:36 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:38 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:40 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:41 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:43 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:44 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:46 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:47 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:49 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:51 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:52 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:54 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:55 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:57 Deploying Barbarian King...failed, will retry
12-Feb-16 23:56:58 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:00 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:02 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:03 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:05 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:06 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:08 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:09 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:11 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:13 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:14 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:16 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:17 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:19 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:20 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:22 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:23 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:25 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:26 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:28 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:29 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:31 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:32 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:34 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:35 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:37 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:38 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:40 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:41 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:43 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:45 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:46 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:48 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:49 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:51 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:52 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:54 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:55 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:57 Deploying Barbarian King...failed, will retry
12-Feb-16 23:57:58 Deploying Barbarian King...failed, will retry
12-Feb-16 23:58:00 Deploying Barbarian King...failed, will retry
12-Feb-16 23:58:01 Deploying Barbarian King...failed, will retry
12-Feb-16 23:58:03 Deploying Barbarian King...failed, will retry
12-Feb-16 23:58:04 Deploying Barbarian King...failed, will retry
12-Feb-16 23:58:06 Deploying Barbarian King...failed, will retry
12-Feb-16 23:58:07 Deploying Barbarian King...failed, will retry
12-Feb-16 23:58:09 Deploying Barbarian King...failed, will retry
12-Feb-16 23:58:10 Deploying Barbarian King...failed, will retry
12-Feb-16 23:58:12 Deploying Barbarian King...failed, will retry
12-Feb-16 23:58:13 Deploying Barbarian King...failed, will retry
12-Feb-16 23:58:15 Deploying Barbarian King...failed, will retry
12-Feb-16 23:58:17 Deploying Barbarian King...failed, will retry
12-Feb-16 23:58:18 Deploying Barbarian King...failed, will retry
12-Feb-16 23:58:20 Deploying Barbarian King...failed, will retry
12-Feb-16 23:58:21 Deploying Barbarian King...failed, will retry
12-Feb-16 23:58:23 Deploying Barbarian King...failed, will retry
12-Feb-16 23:58:24 Deploying Barbarian King...failed, will retry
12-Feb-16 23:58:26 Deploying Barbarian King...failed, will retry
12-Feb-16 23:58:27 Deploying Barbarian King...failed, will retry
12-Feb-16 23:59:00 WaitForBattleEnd() No change in available loot for 30 seconds, ending battle.
12-Feb-16 23:59:00 AutoRaidEndBattle() Clicking End Battle button
12-Feb-16 23:59:05 AutoRaidEndBattle() Clicking End Battle confirmation button
12-Feb-16 23:59:10 Winnings total net change:  Gold:431433 Elix:236957 Dark:573 Cups:42
```

I'm on Windows 10, native (no VM); BlueStacks v0.10

**Comment by CodeSlinger69** [comment]
What level barb king?  I use the appearance of the health bar to indicate whether the barb king has been successfully deployed or not.  I'm wondering if a barb king less than level 5 has a different health bar or something.  Since you are TH7, it wouldn't surprise me if your king is less than L5.  I might have to make an adjustment for L1-L4 kings.

Can you grab a shot of your screen right after your drop your king on the field?  Easiest place to do this is on one of the early goblin maps...that way you don't waste gold searching...

**Comment by opensourceguy123** [comment]
Indeed, I have an L1 barb king. Here's a screenshot of what things look like right after deploying my barb king:

![image](https://cloud.githubusercontent.com/assets/17028765/13028875/f24a93f4-d249-11e5-8b18-beeb669e79fa.png)

Thanks!

**Comment by CodeSlinger69** [comment]
Thanks for the screen shot.  So a L1-L4 king (and I suppose Queen/Warden) does not have a health bar over the button.  Rather, the button turns into a gray scale image once the hero is deployed.  Very interesting.  It was so long ago, I think I just may have forgotten about that behavior.

Can I ask a favor, OSG?  Since I don't have an account to test this on (all my heroes are > 5), I can't grab a screen shot to fix this.  Basically my idea to fix this is simple: to validate hero deployment, I either:
1. Test for the health bar, or
2. Test for the gray scale hero image.

To code up #2, I need a .bmp file with a screen shot like you posted above.  Only .bmp works, as it is the only format that doesn't modify pixels.  To get a .bmp screen shot on GitHub, you need to zip it up, then GitHub will let you attach the file to a post here.

If you could get me a new screen shot in .bmp format, I can have this fixed pretty quickly.  Of course, I'll need your help for gray scale queen and warden images too, eventually.

**Comment by opensourceguy123** [comment]
Sure, I'd love to help out (in however a small way it might be).

Here's the best I can do though. Could you please let me know how I can remove the `View open apps` button? (if it is ok with the button, I'll send over a zipped bmp):

![image](https://cloud.githubusercontent.com/assets/17028765/13030951/0ed3e072-d289-11e5-8e15-e4e1463fd77f.png)

**Comment by chrishubert** [comment]
@opensourceguy123 , you can get a better bmp capture "as seen by the bot" by setting $gDebugSaveScreenCaptures=True in globals.au3, and then look for it in your ClAsHbOt folder.

**Comment by opensourceguy123** [comment]
That doesn't seem to be working unfortunately. This is all I get in the DeployAndMonitorHeros.bmp:

![image](https://cloud.githubusercontent.com/assets/17028765/13031214/4efb65da-d293-11e5-9e22-db0ef246618d.png)

**Comment by CodeSlinger69** [comment]
OSG, the Android system bar overlay in the .bmp file is OK.  I only look at the top 2/3's of image when I am doing matching logic.  It didn't used to be this way - in the Jan 26 CoC client update, SC changed something that made the system bar overlay the game, and I adjusted the bot accordingly.  As an aside, this is a very annoying change - when I play as a human, those buttons get in my way all the time.

Anyway, a screenshot (.bmp format) including the system bar is just fine.  I'll extract only the parts of the image that I need to the match algorithm.

But, that weird image you found in DeployAndMonitorHeros.bmp is strange.  I don't think it is related to the issue of this thread, but it is weird.

BTW, while we are fixing this issue, the bot will work fine for you.  It's just going to click on your King 30 times to try to deploy him, but deploy him it will.

**Comment by opensourceguy123** [comment]
Whoops, sorry, I just put my barb king on upgrade (but to level 2 though, so that icon should hopefully not change). I'll have this in by tomorrow.

> BTW, while we are fixing this issue, the bot will work fine for you. It's just going to click on your King 30 times to try to deploy him, but deploy him it will.

Thanks, indeed he did :). Another temporary work-around I used was to comment out the code responsible for re-launching him if the launch failed. It seems that the launch succeeds most of the time :)

**Comment by opensourceguy123** [comment]
Hey, sorry for the delay. Here's a zip containing the barb king bmp :)

[coc_bk_lv2.zip](https://github.com/CodeSlinger69/ClAsHbOt/files/138914/coc_bk_lv2.zip)

Thanks!

**Comment by CodeSlinger69** [comment]
Commit: https://github.com/CodeSlinger69/ClAsHbOt/commit/cf5c024835b8f1ab37f2167730de3aa8201a0097

I can't test this, OSG, so please let me know if it works.

**Comment by opensourceguy123** [comment]
Thanks! This works great!

Closing this issue.

**Comment by CodeSlinger69** [comment]
Good to hear, but reopening.  Will need gray scale images of the queen and warden eventually, to complete this fix.  My TH8 account is about 2 months from TH9, so if anyone has a L1-L4 queen or warden, please post.

**Comment by DaOneBomb** [comment]
Hello :)
Same thing happening with my level 3 queen so here is the greyed out image:
[queen.zip](https://github.com/CodeSlinger69/ClAsHbOt/files/149803/queen.zip)
Cheers :D

**Comment by CodeSlinger69** [comment]
Awesome, thanks bomb.  Image added, please let us know if it works correctly, as I can't test.
https://github.com/CodeSlinger69/ClAsHbOt/commit/e1273a9e5797fe264226da43eb00172eea30ac9b

**Comment by CodeSlinger69** [comment]
Still looking for a grayed out warden image if anyone has one.

**Comment by YosuaMarchel** [comment]
Can't you get the troop bmp from youtube video? maybe take one from attack video from youtube.

**Comment by CodeSlinger69** [comment]
+thokijo  Nope.  I need the actual pixels from BlueStacks.  Thanks though.

**Comment by CodeSlinger69** [comment]
This project is no longer maintained.
