### ISSUE TITLE
COC Closing automatically after 5-10 seconds after the new update v8.116.11

### ISSUE THREAD

**Issue by abhi-ace** [CodeSlinger69/ClAsHbOt#57]
Hello Everyone COC is closing automatically after some time even if the bot is not opened. The temporary fix is to downgrade it to v8.116.2 but this is just temporary. This is just to let you know @CodeSlinger69. 
A fix for this is appreciated.

ClasHbOt ON!

**Comment by PhuriousGeorge** [comment]
I'm pretty sure the bot isn't the problem. I'm crashing without turning the bot on

**Comment by CodeSlinger69** [comment]
I'm not seeing any issues with the CoC client, or with the bot.  Can you track down what is happening just before the CoC client closes?  Is it consistent/reproducible?

**Comment by CodeSlinger69** [comment]
I've been looking into this.  It is a very common problem, being reported everywhere from other botting forums, to SuperCell's forums.  As this is not a ClAsHbOt specific issue, I'll close this thread.

**Comment by CodeSlinger69** [comment]
FYI: https://mybot.run/forums/index.php?/announcement/13-clash-of-clans-closingcrashing-on-you-read-here/
