### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by xzb667** [CodeSlinger69/ClAsHbOt#59]
Where can I find build instructions for CIAsHbOt?

thanks
xzb667

**Comment by CodeSlinger69** [comment]
Building the C++ DLL, you mean?  In that case, I haven't written it up yet, but it is a good idea.  I'll add a wiki page in the coming days for this.

**Comment by xzb667** [comment]
thanks!
xzb667

**Comment by xzb667** [comment]
where/how does the au3 script source get compiled?

**Comment by CodeSlinger69** [comment]
The AutoIt script compilation is pretty straightforward:  Open up ClAsHbOt.au3 in your AutoIt script editor ("SciTE"), then go to Tools/Compile.

**Comment by CodeSlinger69** [comment]
Wiki: https://github.com/CodeSlinger69/ClAsHbOt/wiki/Compilation-Instructions

Please let me know how I can make this easier to understand, if needed.
