### ISSUE TITLE
Add option to donate troops to clan mates

### ISSUE THREAD

**Issue by CodeSlinger69** [CodeSlinger69/ClAsHbOt#6]
Detect troop requests, parse request text, and fill appropriately.

**Comment by CodeSlinger69** [comment]
First commit made on this.  Will auto-donate troops that are "in stock", based on parsing the request text.  Interpretation of the parsed text is configurable in the ini file.

The next commit will handle the queuing of troops to a defined "stock" level, so that requests can be filled.

**Comment by CodeSlinger69** [comment]
Complete for in-stock troops.

In-stock troops are either 1) troops queued up by the auto-raid function, or 2) troops you have manually queued up in your barracks.  As of now, I don't plan on implementing an automatic way to queue up troops other than those needed for auto-raid.  This is difficult logic, and would likely require taking over one or more barracks just for this function, which would interfere with farming. Since this is primarily a farm bot, I am going to hold off on this, unless I get a magical inspiration on a good way to do this.

https://github.com/CodeSlinger69/ClAsHbOt/releases/tag/20150509

**Comment by Stormtrail** [comment]
The way you have this implemented, what's the correct way to handle donation text strings? It parses most of them just fine, but have seen a few where I'm unclear if its better to make a new string, or append more options.

For example:

6/16/2015 11:04:17 AM DonateTroops()
6/16/2015 11:04:18 AM Donate button found at absolute: 97, 152, 179, 177
6/16/2015 11:04:18 AM Donate text: 'wizards or archers plz'
6/16/2015 11:04:19 AM Donate troops window opened.
6/16/2015 11:04:19 AM Donate loop 1 of 5
6/16/2015 11:04:19 AM Troop DonateBarbarian.bmp found at 193, 76 conf: 99.92%
6/16/2015 11:04:19 AM Troop DonateArcher.bmp found at 263, 77 conf: 99.93%
6/16/2015 11:04:19 AM Troop DonateHogRider.bmp found at 470, 160 conf: 99.54%
6/16/2015 11:04:19 AM String match for: Wizard, troop NOT available, exiting.

I would think that it would also find the archers request but it doesn't appear to here.

6/16/2015 11:13:51 AM DonateTroops()
6/16/2015 11:13:52 AM Donate button found at absolute: 97, 152, 179, 177
6/16/2015 11:13:52 AM Donate text: 'lootdefence'
6/16/2015 11:13:52 AM Donate troops window opened.
6/16/2015 11:13:52 AM Donate loop 1 of 5
6/16/2015 11:13:52 AM Troop DonateBarbarian.bmp found at 193, 76 conf: 99.92%
6/16/2015 11:13:52 AM Troop DonateArcher.bmp found at 263, 77 conf: 99.93%
6/16/2015 11:13:52 AM Troop DonateGiant.bmp found at 331, 76 conf: 99.8%
6/16/2015 11:13:53 AM Troop DonateHogRider.bmp found at 470, 160 conf: 99.54%
6/16/2015 11:13:53 AM Could not find a fill for request, exiting.

If I want to handle the keyword "def" with a default donation of archer, or allow archers as a default donation for almost anything that doesn't say war/air/dark for example what's the best way to implement that? All handled from within the .ini?

**Comment by Stormtrail** [comment]
6/16/2015 6:06:10 PM Donate text: 'arch wiz min'
6/16/2015 6:06:10 PM Donate troops window opened.
6/16/2015 6:06:10 PM Donate loop 1 of 5
6/16/2015 6:06:10 PM Troop DonateArcher.bmp found at 263, 120 conf: 99.89%
6/16/2015 6:06:10 PM String match for: Wizard, troop NOT available, exiting.

Just another log message example.
