### ISSUE TITLE
Alert: New FairPlay intent

### ISSUE THREAD

**Issue by CodeSlinger69** [CodeSlinger69/ClAsHbOt#62]
See here: http://forum.supercell.net/showthread.php/1102359-Encouraging-Fairplay

I don't think anyone knows exactly what this means, quite yet.  Seems like they are giving people a grace period to remove "forbidden" software from their devices, but have not yet started enforcement.  At least that is how I read it.

Clearly ClAsHbOt falls squarely in the cross-hairs of this latest move by SC.  I would advise caution and restraint in botting for a while, at least until we see how this falls out.

I am not resting, however, as I anticipated this day a long time ago.  My bot already clicks in a human like fashion, and I have the ability to further "humanize" the bot if needed.  The algorithms are there in the bot already (or on my hard drive), and are just waiting to be implemented.

The use of BlueStacks is NOT a bannable offense.  And since my bot operates outside of BlueStacks, the only way to detect is operation is via click pattern analysis, or by being reported by another player.

I can't control other players' reporting, but I can foil their attempts at click pattern analysis.  Let's see how this plays out over the next few weeks and I'll explore options.

In the meantime, be careful.  Don't bot 24x7, don't brag to your clan mates, etc.  Keep a low profile in other words.

**Comment by CodeSlinger69** [comment]
MBR thread here: https://mybot.run/forums/index.php?/topic/18375-sc-cracking-down-on-mods-and-bots/

**Comment by opensourceguy123** [comment]
Yeah, just noticed this too. Maybe it's time to add back [random delays](https://github.com/CodeSlinger69/ClAsHbOt/pull/55) everywhere?

Also, not sure how well this will work, but perhaps each option can represent an "upper bound" now? So train every 5 minutes, for example, would now train randomly after an interval [5 minutes/y, 5 minutes], for some y (say 2 or 4)?

**Comment by CodeSlinger69** [comment]
Yes, more human-like randomness (weighted random, not true random) is one part of this.  I would also like to:
1. Adjust/randomize the troop drops on attacks.  Might finally need to address the red-line as well.
2. Log off when training troops.  
3. Respect PBT - log off for a while when it happens maybe.
4. Click/drag to deploy troops, rather than clicking once for each troop that gets deployed

And other ideas.  Just things that I never bothered with before, as SC just didn't seem to care.  Before I start furiously coding, I am going to monitor the actual bans.  If they are banning XMOD users, that is one thing, but if botters start getting banned then I will start getting busy.  I'm watching the MBR forums for now, very vibrant community over there.

**Comment by CodeSlinger69** [comment]
New commit: https://github.com/CodeSlinger69/ClAsHbOt/commit/58abedd8adc9c531de27fe9994b9db49e9a0c985
- Removed Auto Push - AutoPush is no longer viable with the TownHalls being moved inside bases.  This is a legacy option that should have been removed long ago.
- Restored the human-like popping of loot bubbles that was removed a few releases ago for vanity reasons.  Bubbles are now popped in a more more undetectable manner.
- Removed Defense Farm - This was something I added in anticipation of SC eventually giving a loot bonus for successful defenses.  As this never happened, this option gets removed.  If you still want to get the unbreakable achievement, just do normal raiding in Silver - set dump cups to <800 or so, and the defense wins will just pile up naturally.
- Auto Raid now goes offline while waiting for troops/heroes - I now utilize the build time remaining indicator on the top right of the army overview screen.  The bot will take Clash offline until troops are done being built.  Human players don't check the army overview screen every few minutes to see if their troops are ready.  Unfortunately, heroes don't have a similar indicator, so if you have "Wait for heroes" set as an option, the bot will take Clash offline for a random period of time, and check in on hero readiness periodically.  Hopefully SC will add a hero indicator in a later release as well.

**Comment by CodeSlinger69** [comment]
So far it looks like SC is only banning XMOD/IMOD users.  There have been zero reports of people being banned only for botting, on any of the botting forums.  Most botters who have been banned have also been using one of the mod tools.

It seems like botting is safe for the time being, then.  But as usual, be careful - only bot a human-like amount per day.  Mix it up - use a number of different bots, so that individual bot's "signatures" get all jumbled up with other bot's signatures.  Play some manual Clash in between botting sessions.  Mixing it up like this will foil their attempts to detect botting by looking for patterns.

I will of course, continue to work on the human-like algorithms :)

**Comment by CodeSlinger69** [comment]
Closing issue. SC's FP initiative seems not to be targetting botters.  XMOD users, yes, botters no.  Bot safely, not more than a normal amount of human  hours per day, use different bots to mess up their "bot signature" detection (if it exists), and you should be fine.
