### ISSUE TITLE
magematch-dll request please

### ISSUE THREAD

**Issue by kevinjack** [CodeSlinger69/ClAsHbOt#65]
hello,
I need the ImageMatch dll source to rebuild it with custom modifications but dont know where to download it again. Would you please send me the DLL source please. :) Thanks for helping. You can upload it to anywhere and place a download link there or send to my Email please: giahh263@gmail.com. 
Thanks.

**Comment by CodeSlinger69** [comment]
Full source code is right here on GitHub.  https://github.com/CodeSlinger69/ClAsHbOt/tree/master/Source

Always has been, always will be.
