### ISSUE TITLE
Bluestacks wrong size error

### ISSUE THREAD

**Issue by muoitranduc** [CodeSlinger69/ClAsHbOt#67]
Hello there,
Thanks for the great works so far.
I try to open your application, it returns Bluestacks wrong size error (Hit Ok to resize...).
However, even when I hit OK, and try to modify the Bluestack resolution by regedit to 860x733, the errors keep appearing. Note that there is no .reg file in Bluestack folder..

**Comment by ahxxm** [comment]
although I found .reg file [here](https://github.com/CodeSlinger69/ClAsHbOt/blob/master/Helpers/BlueStacks/860x733.reg) and imported it, the errors keep appearing.
![image](https://cloud.githubusercontent.com/assets/1286225/18072438/e91c6daa-6e90-11e6-9ae7-bc713b2d303c.png)

**Comment by CodeSlinger69** [comment]
This project is no longer maintained.
