### ISSUE TITLE
Stuck at Star Bonus/disconnected screen

### ISSUE THREAD

**Issue by opensourceguy123** [CodeSlinger69/ClAsHbOt#68]
Latest few versions of ClAsHbOt get stuck at the star bonus screen:

![image](https://cloud.githubusercontent.com/assets/17028765/17934949/5a822844-6a37-11e6-9278-c64395dbfcfa.png)

Don't know the exact version from which this started, but I think this was not happening before.

PS: I will keep saying this each time I post an issue: I <3 ClAsHbOt

**Comment by opensourceguy123** [comment]
The bot also gets stuck on similar screens ("Disconnected due to inactivity", "Connection Lost: You have lost your connection with the server. Check your internet and try again"). The screens themselves are not the bot's fault, just that it doesn't recover if such a screen is hit. Can bot be configured to automatically hit the "Reload game" button any time such a popup appears?

**Comment by EllieWatson** [comment]
Free download latest version everything unlimited fully [cracked apk](https://webhax.xyz/category/android-apps/) & [mod apk](https://webhax.xyz/category/android-games/).. [coc mod apk ](https://webhax.xyz/coc-mod-apk/)

**Comment by CodeSlinger69** [comment]
This project is no longer maintained.
